local_costmap:

  #Set the global and robot frames for the costmap
  global_frame: odom
  robot_base_frame: base_link

  #Set the update and publish frequency of the costmap
  update_frequency: 5.0
  publish_frequency: 5.0

  #We'll configure this costmap to be a rolling window... meaning it is always centered at the robot
  static_map: false
  rolling_window: true
  width: 6.0
  height: 6.0
  resolution: 0.05