target_frame: kinect
min_height: 0.0
max_height: 1.5
angle_min: -1.5708
angle_max: 1.5708
angle_increment: 0.0087
scan_time: 0.3333
range_min: 0.45
range_max: 5.0
concurrency_level: 1
use_inf: true
# 1.5708