<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="swc">
    <!-- ROBOT DIMENSIONS -->
    <xacro:property name="wheel_len" value="0.05"/>
    <xacro:property name="wheel_diam" value="0.2" />
    <xacro:property name="pi" value="3.1415" />
    <xacro:property name="box_length" value="0.50"/>
    <xacro:property name="box_width" value="0.50"/>
    <xacro:property name="box_height" value="0.25"/>
    <xacro:property name="wheel_mass" value="0.2"/>
    <xacro:property name="box_mass" value="8"/>
    <xacro:property name="kinect_length" value="0.08"/>
    <xacro:property name="kinect_width" value="0.2"/>
    <xacro:property name="kinect_height" value="0.1"/>
    <xacro:property name="kinect_mass" value="0.01"/>

    <xacro:include filename="$(find project)/urdf/robot.gazebo"/>

    <material name="blue">
        <color rgba="0 0 0.8 0.75" />
    </material>
    <material name="white">
        <color rgba="1 1 1 1" />
    </material>
    <material name="black">
        <color rgba="0.05 0.05 0.05 1" />
    </material>



    <link name="base_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="${box_length} ${box_width} ${box_height}"/>
            </geometry>
            <material name="blue"/>
        </visual>

        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="${box_length} ${box_width} ${box_height}"/>
            </geometry>
        </collision>

        <inertial>   <!-- CHANGE HERE THE REAL MASS AND INTERIA VALUES OF OUR ROBOT-->
            <mass value="${box_mass}" />
            <inertia ixx="0.625" ixy="0.0" ixz="0.0" iyy="1" iyz="0.0" izz="0.625" />
        </inertial>

<!--        THE CASTER-->
        <visual name="caster">
            <origin xyz="-0.20 0 -0.12" rpy="0 0 0" />
            <geometry>
                <sphere radius="0.05" />
            </geometry>
            <material name="black" />
        </visual>
        <collision>
            <origin xyz="-0.2 0 -0.12" rpy="0 0 0" />
            <geometry>
                <sphere radius="0.05" />
            </geometry>
        </collision>
        <inertial>
            <mass value="0.25" />
            <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001" />
        </inertial>
    </link>


    <xacro:macro name="wheel" params="prefix_x prefix_y reflect_x reflect_y">

        <link name="${prefix_x}_${prefix_y}_wheel">
            <visual>
                <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
                <geometry>
                    <cylinder length="${wheel_len}" radius="${wheel_diam/2}"/>
                </geometry>
            </visual>

            <collision>
                <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
                <geometry>
                    <cylinder length="${wheel_len}" radius="${wheel_diam/2}"/>
                </geometry>
            </collision>

            <inertial>  <!-- CHANGE WHEEL INTERIAL VALUES HERE -->
                <mass value="${wheel_mass}"/>
                <inertia ixx="0.0008" ixy="0.0" ixz="0.0" iyy="0.0008" iyz="0.0" izz="0.0015" />
            </inertial>
        </link>

        <joint name="${prefix_x}_${prefix_y}_wheel_joint" type="continuous">
            <parent link="base_link"/>
            <child link="${prefix_x}_${prefix_y}_wheel"/>
            <origin xyz="${reflect_x*((box_length/2)-0.0)-(reflect_x*(wheel_diam/2))} ${reflect_y*(((wheel_len))+(box_width/2))} -0.07" rpy="0 0 0"/>
            <axis xyz="0 1 0"/>
            <limit effort="300.0" velocity="100.0"/>
        </joint>


        <!--TRANSMISSION TO TELL GAZEBO WHAT TO DO WITH THIS JOINT (SHAFTS)-->
        <transmission name="${prefix_x}_${prefix_y}_shaft_trans">
            <type>transmission_interface/SimpleTransmission</type>
            <actuator name="${prefix_x}_${prefix_y}_wheel_motor">
                <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
            <joint name="${prefix_x}_${prefix_y}_wheel_joint">
                <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
            </joint>
        </transmission>

        <!-- SOME PHYSICAL PROPERTIES FOR THE WHEELS TO BE SIMULATED-->
        <gazebo reference="${prefix_x}_${prefix_y}_wheel">
            <mu1 value="200.0"/>
            <mu2 value="100.0"/>
            <kp value="1000000.0" />
            <kd value="1.0" />
            <material>Gazebo/Grey</material>
        </gazebo>

    </xacro:macro>
    <xacro:wheel prefix_x="front" prefix_y="right" reflect_x="1" reflect_y="-1"/>
    <xacro:wheel prefix_x="front" prefix_y="left" reflect_x="1" reflect_y="1"/>
<!--    <xacro:wheel prefix_x="back" prefix_y="right" reflect_x="-1" reflect_y="-1"/>-->
<!--    <xacro:wheel prefix_x="back" prefix_y="left" reflect_x="-1" reflect_y="1"/>-->



    <!-- LINK AND JOINT FOR THE KINECT CAMERA-->
    <link name="kinect">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://project/mesh/kinect.dae"/>
            </geometry>
        </visual>

        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="${kinect_length} ${kinect_width} ${kinect_height}"/>
            </geometry>
        </collision>

        <inertial>
            <mass value="${kinect_mass}"/>
            <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6"/>
        </inertial>
    </link>

    <joint name="kinect_joint" type="fixed">
        <parent link="base_link"/>
        <child link="kinect"/>
        <origin xyz="${(box_length/2)-(kinect_length/2)} 0 ${(box_height/2)+(kinect_height/2)}"/>
    </joint>


        <!-- kinect optical link for fixing the point cloud view-->
    <link name="kinect_optical">
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.15 0.30 0.15"/>
            </geometry>
        </collision>
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <box size="0.05 0.05 0.05"/>
            </geometry>
        </visual>
        <inertial>
            <mass value="1e-5" />
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
        </inertial>
    </link>

    <joint name="kinect_optical_joint" type="fixed">
        <axis xyz="0 1 0"/>
        <origin xyz="0 0 0" rpy="-1.57 0 -1.57"/>
        <parent link="kinect"/>
        <child link="kinect_optical"/>
    </joint>


    <link name="imu_sensor">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.05 0.05 0.02"/>
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.05 0.05 0.02"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="1e-5" />
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
        </inertial>
    </link>

    <joint name="imu_sensor_joint" type="fixed">
        <parent link="base_link"/>
        <child link="imu_sensor"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>
    
</robot>